import type { NewPin } from "./schema";

export const seedPins: NewPin[] = [
  {
    slug: "la-abuela",
    number: 1,
    title: "La Abuela",
    subtitle: "Block C — north facade",
    artist: "Roque Espinoza",
    category: "mural",
    year: "2024",
    accent: "#E4572E",
    x: 26,
    y: 31,
    imageUrl: "/images/mural-1.jpg",
    body:
      "Four storeys of raw concrete turned into a portrait of the women who arrived here in the seventies, carrying the countryside in their suitcases. The painter grew up two streets away. He mixed the ochres on the pavement while neighbours passed down buckets of water from the third floor.",
    quote:
      "We did not want a decoration. We wanted the building to look back at us.",
    quoteAuthor: "Roque Espinoza, painter",
  },
  {
    slug: "escalera-geometrica",
    number: 2,
    title: "Escalera Geométrica",
    subtitle: "Stairwell 14, passage to the market",
    artist: "Matteo Negri",
    category: "intervention",
    year: "2025",
    accent: "#1D7874",
    x: 48,
    y: 22,
    imageUrl: "/images/mural-2.jpg",
    body:
      "For years this passage was a place you crossed quickly and without looking up. Teal, coral and a hard yellow now bend around the handrails, so that the geometry changes with every step you take. Children use the coloured bands as a hopscotch grid on their way to school.",
    quote: "Colour is the cheapest form of street lighting.",
    quoteAuthor: "Neighbourhood assembly, Sector 2",
  },
  {
    slug: "la-cancha",
    number: 3,
    title: "La Cancha",
    subtitle: "Community court, central square",
    artist: "Collective work — 60 residents",
    category: "public space",
    year: "2025",
    accent: "#E8A33D",
    x: 62,
    y: 55,
    imageUrl: "/images/mural-3.jpg",
    body:
      "The concrete court sat empty for the best part of a decade. It was repaired, repainted and given back in a single weekend of communal work: the lines were drawn by teenagers, the graphic surface designed with the people who play on it every evening. The first match after the reopening lasted until the floodlights failed.",
    quote: "Ours again, and this time in daylight.",
    quoteAuthor: "Marisol, resident since 1979",
  },
  {
    slug: "raices",
    number: 4,
    title: "Raíces",
    subtitle: "Block H — west gable",
    artist: "Beatrice Vigoni",
    category: "mural",
    year: "2024",
    accent: "#5B8C5A",
    x: 34,
    y: 68,
    imageUrl: "/images/mural-4.jpg",
    body:
      "Maize, ceiba leaves and two volcanoes, painted in indigo and deep green over a wall that had been grey since it was poured. The composition follows the rain stains of forty winters instead of hiding them; up close you can still read the history of the concrete underneath.",
    quote: "The wall already had a drawing. We only followed it.",
    quoteAuthor: "Beatrice Vigoni, artist",
  },
  {
    slug: "el-mirador",
    number: 5,
    title: "El Mirador",
    subtitle: "Rooftop, Block A",
    artist: "Adriano Lombardo",
    category: "light",
    year: "2025",
    accent: "#B6465F",
    x: 74,
    y: 34,
    imageUrl: "/images/map.jpg",
    body:
      "A low line of warm lamps installed along the highest roof of the superblock. Seen from the valley, it draws the outline of the colonia after dark — the first time in decades the neighbourhood is visible at night as a shape rather than an absence.",
    quote: "From the bus you can finally see where you live.",
    quoteAuthor: "Kevin, 17",
  },
  {
    slug: "la-tienda",
    number: 6,
    title: "La Tienda de Doña Chepi",
    subtitle: "Ground floor, Block D",
    artist: "Giuseppe De Mattia",
    category: "archive",
    year: "2025",
    accent: "#E4572E",
    x: 54,
    y: 78,
    imageUrl: "/images/mural-2.jpg",
    body:
      "A corner shop that closed under extortion and reopened in 2025. Its shutter now carries a photographic archive printed directly on metal: family pictures loaned by twelve households, scanned on a table in the courtyard over three afternoons.",
    quote: "Everyone came to see if their grandmother made it onto the door.",
    quoteAuthor: "Doña Chepi, shopkeeper",
  },
  {
    slug: "pasaje-del-agua",
    number: 7,
    title: "Pasaje del Agua",
    subtitle: "Alley between Blocks E and F",
    artist: "Satoshi Gallery",
    category: "intervention",
    year: "2026",
    accent: "#2F6690",
    x: 18,
    y: 52,
    imageUrl: "/images/mural-3.jpg",
    body:
      "Painted gutters and blue mosaic run the length of the alley, following the path the rainwater actually takes in the wet season. During a storm the artwork fills up and moves. The mosaic tiles were cut from broken floor tiles collected door to door.",
    quote: "In October the painting starts to flow.",
    quoteAuthor: "Field notes, Sector 4",
  },
  {
    slug: "memoria",
    number: 8,
    title: "Memoria",
    subtitle: "Wall of the old health post",
    artist: "Andrea Ravo Mattoni",
    category: "memory",
    year: "2026",
    accent: "#8C6A5D",
    x: 84,
    y: 66,
    imageUrl: "/images/mural-1.jpg",
    body:
      "The quietest wall of the colonia. A classical composition repainted at 1:1 scale, dedicated to the people the neighbourhood lost during the conflict of the eighties. No names are written on it; residents leave flowers at its base on the first Sunday of every month.",
    quote: "Some walls are for looking at in silence.",
    quoteAuthor: "Custodians of the wall",
  },
];
